 name: Trigger Remote Workflow

 on:
  push:
    # pull_request:
    #   types:
    #     [ labeled ]

 jobs:
   test-test:
     # if: contains(github.event.label.name, 'run-pro-test')
     runs-on: ubuntu-latest
     steps:
       - name: Extract branch name
         shell: bash
         run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
         id: extract_branch

       - name: Trigger Remote Workflow
         run: |
            response=$(curl -X POST \
             -H "Authorization: token ${{ secrets.REMOTE_GITHUB_KEY }}" \
             -H "Accept: application/vnd.github.v3+json" \
             -d '{"event_type": "run-pro-tests", "client_payload": {"branch": "${{ steps.extract_branch.outputs.branch }}"}}' \
             https://api.github.com/repos/baghdasarovelementor/test-pro/dispatches)
